name: Build and Publish Executable

on:
  push:
    branches:
      - main

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Adjust based on your project needs

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Executable
      run: |
        pyinstaller --onefile your_script.py
        mkdir build_artifacts
        move dist\your_script.exe build_artifacts\your_script.exe

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: precompiled-executable
        path: build_artifacts/
